server:
  servlet:
    context-path: "/dev"

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # auto: create # 开发阶段使用
          auto: update
  flyway:
    enabled: false # 启用或禁用 flyway


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        #cache: TRACE
        cache: INFO
      hibernate:
        tool:
          hbm2ddl: DEBUG
          # 输出数据库模型（开发阶段）

starcoin:
  dao-sbt-resource-struct-tag-format: "0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x6bfb460477adf9dd0455d3de2fc7f211::SBTModule::DaoMember<%1$s>, 0x6bfb460477adf9dd0455d3de2fc7f211::SBTModule::DaoMemberBody<%1$s>>"
  identifier-nft-sbt-value-bcs-path: "{option<{address,u64,{bytes,bytes,bytes,bytes},{u64},{{u128}}}>}[0][0][4][0][0]"
