/* Generated By:JavaCC: Do not edit this line. TypeParserConstants.java */
package org.starcoin.bcs.sab;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TypeParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int LT = 5;
    /**
     * RegularExpression Id.
     */
    int GT = 6;
    /**
     * RegularExpression Id.
     */
    int LPAREN = 7;
    /**
     * RegularExpression Id.
     */
    int RPAREN = 8;
    /**
     * RegularExpression Id.
     */
    int LBRACE = 9;
    /**
     * RegularExpression Id.
     */
    int RBRACE = 10;
    /**
     * RegularExpression Id.
     */
    int LBRACKET = 11;
    /**
     * RegularExpression Id.
     */
    int RBRACKET = 12;
    /**
     * RegularExpression Id.
     */
    int COMMA = 13;
    /**
     * RegularExpression Id.
     */
    int DOT = 14;
    /**
     * RegularExpression Id.
     */
    int UNDERSCORE = 15;
    /**
     * RegularExpression Id.
     */
    int UINTEGER = 16;
    /**
     * RegularExpression Id.
     */
    int DIGIT = 17;
    /**
     * RegularExpression Id.
     */
    int VECTOR = 18;
    /**
     * RegularExpression Id.
     */
    int STRUCT = 19;
    /**
     * RegularExpression Id.
     */
    int OPTIONAL = 20;
    /**
     * RegularExpression Id.
     */
    int ENUM = 21;
    /**
     * RegularExpression Id.
     */
    int BYTES = 22;
    /**
     * RegularExpression Id.
     */
    int STRING = 23;
    /**
     * RegularExpression Id.
     */
    int U128 = 24;
    /**
     * RegularExpression Id.
     */
    int U64 = 25;
    /**
     * RegularExpression Id.
     */
    int U8 = 26;
    /**
     * RegularExpression Id.
     */
    int BOOL = 27;
    /**
     * RegularExpression Id.
     */
    int ADDRESS = 28;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\r\"",
            "\"\\t\"",
            "\"\\n\"",
            "\"<\"",
            "\">\"",
            "\"(\"",
            "\")\"",
            "\"{\"",
            "\"}\"",
            "\"[\"",
            "\"]\"",
            "\",\"",
            "\".\"",
            "\"_\"",
            "<UINTEGER>",
            "<DIGIT>",
            "\"vector\"",
            "\"struct\"",
            "\"option\"",
            "\"enum\"",
            "\"bytes\"",
            "\"string\"",
            "\"u128\"",
            "\"u64\"",
            "\"u8\"",
            "\"bool\"",
            "\"address\"",
    };

}
